ardueshop/ardueshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
        path("product/", include("product.urls", namespace="product")),
        path("catalogue/", include("product.urls", namespace="catalogue")),
        path("cart/", include("cart.urls", namespace="cart")),
        path("order/", include("order.urls", namespace="order")),
        path("payment/", include("payment.urls", namespace="payment")),
        path(
            "", include("base.urls")
        ),  # This path must be the last one because it will match any URL
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

ardueshop/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path('order_not_found/', views.order_not_found, name='order_not_found'),
    path('sales_report/', views.sales_report, name='sales_report')
]

ardueshop/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path('<int:id>/', views.order_status, name='order_status'),
    path("<int:order_id>/claim/new_claim", views.new_claim, name="do_claim"),
    path("claim/<int:claim_id>", views.claim, name="claim"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("order_placed/", views.order_placed, name="order_placed"),
    path("all_orders/", views.all_orders, name="all_orders"),
    path("claims/", views.list_claims, name="list_claims"),
    path('order_not_found/', views.order_not_found, name='order_not_found')
]

ardueshop/payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = "payment"

urlpatterns = [
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webhook, name="stripe_webhook"),
]

ardueshop/product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('', views.catalogue, name='catalogue'),
    path('<int:id>/publishOpinion/', views.publish_opinion, name='publish_opinion'),
    path("search/", views.search_products, name="search_products"),
]

ardueshop/payment/forms.py
from django import forms


class SaveDataForm(forms.Form):
    save_data_checkbox = forms.BooleanField(required=False, initial=True)

ardueshop/payment/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from order.models import Order
from authentication.models import ArduUser
from .forms import SaveDataForm


def payment_completed(request):
    form = SaveDataForm()
    if request.method == "POST":
        form = SaveDataForm(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            ardu_user = ArduUser.objects.get(user=user)
            order = Order.objects.get(id=request.session.get("order_id"))
            if form.cleaned_data["save_data_checkbox"]:
                user.first_name = order.first_name
                user.last_name = order.last_name
                user.save()
                ardu_user.address = order.address
                ardu_user.postal_code = order.postal_code
                ardu_user.city = order.city
                ardu_user.save()

            else:
                user.first_name = ""
                user.last_name = ""
                user.save()
                ardu_user.address = None
                ardu_user.postal_code = None
                ardu_user.city = None
                ardu_user.save()

            return redirect(reverse("catalogue:catalogue"))

    return render(request, "payment/completed.html", {"form": form})


def payment_canceled(request):
    # Delete the order
    order = Order.objects.get(id=request.session.get("order_id"))
    order.delete()
    return render(request, "payment/canceled.html")

ardueshop/payment/templates/payment/canceled.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}- Pago cancelado{% endblock %}

{% block content %}

<div class="container mt-4">
    <div class="card text-center">
        <div class="card-body">
            <h1 class="card-title">¡Pago cancelado!</h1>
            <p class="card-text">Tu pago ha sido cancelado.</p>
            <a href="{% url "product:catalogue" %}" class="btn btn-primary">Volver a la tienda</a>
        </div>
    </div>
</div>

{% endblock %}

ardueshop/payment/templates/payment/completed.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}- Pago completado{% endblock %}

{% block content %}

<div class="container mt-4">
    <div class="card text-center">
        <div class="card-body">
            <h1 class="card-title">¡Pago completado! El ID para el seguimiento de tu pedido es {{request.session.order_id}}</h1>
            <p class="card-text"> Puedes consultar el estado de tu pedido en
                <a href="{% url "order:my_orders" %}">este enlace</a>.
            </p>
            <p class="card-text">Gracias por tu compra.</p>
            <p class="card-text">Recibirás un correo electrónico de confirmación pronto.</p>

            {% if user.is_authenticated %}
            <form method="post" class="form-check">
                {% csrf_token %}
                <div class="mb-4">
                    {{ form.save_data_checkbox }}
                    <label class="form-check-label" for="{{ form.save_data_checkbox.id_for_label }}">
                        Guardar mis datos para futuras compras
                    </label>
                </div>
                <input type="submit" value="Volver a la tienda" class="btn btn-primary">
            </form> 
            {% else %}
            <a href="{% url "product:catalogue" %}" class="btn btn-primary">Volver a la tienda</a>
            <a href="{% url "order:order_status" request.session.order_id %}" class="btn btn-primary">Ver mi pedido</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}