ardueshop/ardueshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
        path("product/", include("product.urls", namespace="product")),
        path("catalogue/", include("product.urls", namespace="catalogue")),
        path("cart/", include("cart.urls", namespace="cart")),
        path("order/", include("order.urls", namespace="order")),
        path("payment/", include("payment.urls", namespace="payment")),
        path(
            "", include("base.urls")
        ),  # This path must be the last one because it will match any URL
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

ardueshop/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path('order_not_found/', views.order_not_found, name='order_not_found'),
    path('sales_report/', views.sales_report, name='sales_report')
]

ardueshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

ardueshop/product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('', views.catalogue, name='catalogue'),
    path('<int:id>/publishOpinion/', views.publish_opinion, name='publish_opinion'),
    path("search/", views.search_products, name="search_products"),
]

ardueshop/base/views.py
from django.shortcuts import render, redirect
from product.models import Category, Product
from order.models import Order, OrderItem
from datetime import timedelta
from django.db.models import Count, Sum
from django.utils import timezone

def home(request):
    products = Product.objects.all().order_by("?")[:3]
    categories = Category.objects.all()
    return render(request, "base/home.html", {"categories": categories, "products": products})

def about(request):
    return render(request, "base/about.html")
def order_not_found(request):
    return render(request, "order/order_not_found.html")

def sales_report(request):
    user = request.user
    if user.is_staff:
        current_date = timezone.now()

        # Calculate the start date for the last 30 days
        last_30_days_start = current_date - timedelta(days=30)

        # Query to get the number of orders from the last 30 days
        orders_last_30_days = Order.objects.filter(
            created__range=(last_30_days_start, current_date)
        )

        number_of_orders_last_30_days = orders_last_30_days.count()

        # Calculate the total price and count of orders
        total_price_last_30_days = sum(order.get_total_cost() for order in orders_last_30_days)

        if number_of_orders_last_30_days > 0:
            average_price_last_30_days = total_price_last_30_days / number_of_orders_last_30_days
        else:
            average_price_last_30_days ="Sin pedidos en los últimos 30 días"
        
        all_orders = Order.objects.all()
        total_benefits = sum(order.get_total_cost() for order in all_orders)

        preferred_shipping_last_30_days = orders_last_30_days.values('shipping_method').annotate(shipping_count=Count('shipping_method')).order_by('-shipping_count').first()

        if preferred_shipping_last_30_days:
            preferred_shipping_option = preferred_shipping_last_30_days['shipping_method']
        else:
            preferred_shipping_option = "Sin pedidos en los últimos 30 días"

        most_popular_products = OrderItem.objects.filter(
            order__created__range=(last_30_days_start, current_date)
        ).values('product__id', 'product__name').annotate(total_quantity=Sum('quantity')).order_by('-total_quantity')[:5]

        # Retrieve product details for the most popular products
        popular_products = []
        for popular_product in most_popular_products:
            product_id = popular_product['product__id']
            total_quantity = popular_product['total_quantity']
            product = Product.objects.get(id=product_id)
            popular_products.append({'product': product, 'total_quantity': total_quantity})



        return render(request, "base/sales_report.html",{
            "number_of_orders_last_30_days": number_of_orders_last_30_days,
            "average_price_last_30_days": average_price_last_30_days,
            "total_price_last_30_days": total_price_last_30_days,
            "total_benefits": total_benefits,
            "preferred_shipping_option": preferred_shipping_option,
            "popular_products": popular_products,
        })
    else:
        return redirect("/auth/login")        # Get the current date and time in the current time zone

ardueshop/base/templates/base/about.html
{% extends 'base/base.html' %}

{% block title %}- Sobre Nosotros{% endblock %}

{% block content %}
  <div class="container" style="padding-top: 20px; display: flex;">

    <!-- Contenedor para el video (a la izquierda) -->
    <div style="flex: 1; padding: 10px;">
      <video width="560" height="315" autoplay loop muted style="width: 100%;">
        <source src="../../../static/video_us.mp4" type="video/mp4">
      </video>
    </div>

    <!-- Contenedor para el texto (a la derecha) -->
    <div style="flex: 1; border: 1px solid black; padding: 20px;">
      <h4>Sobre Nosotros</h4>
      <p>Ardueshop es una tienda online de productos electrónicos, en la que podrás encontrar todo tipo de componentes electrónicos, desde placas Arduino hasta sensores y actuadores.</p>

      <h4>Contacto</h4>
      <p>Si tienes cualquier duda o sugerencia, puedes ponerte en contacto a través de nuestra <a href="https://www.us.es">página web</a></p>
      <p>Teléfono: (+34) 954 55 10 00</p>
      <p>Dirección: Calle San Fernando, 4, 41004, Sevilla</p>
    </div>

  </div>
{% endblock %}

ardueshop/base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% load static %}

  <link rel="icon" href="{% static 'FaviconArduEshop.png' %}" type="image/png">
  <title>Ardueshop {% block title %}{% endblock %}</title>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <!-- Add a link to Google Fonts to import the desired font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <!-- Add a link to the icons from Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>

    <style>
        /* Apply the font to specific elements */
        body {
            font-family: 'Roboto', sans-serif;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        a {
            font-family: 'Roboto', sans-serif;
        }

        main {
            flex: 1;
        }
    </style>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'LogoArduEshop.png' %}" alt="US" class="img-fluid col-md-3" style="width: 200px;">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                {% if user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Administración
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                            <li><a class="dropdown-item" href="/order/claims/">Reclamaciones</a></li>
                            <li><a class="dropdown-item" href="/order/all_orders/">Pedidos</a></li>
                            <li><a class="dropdown-item" href="/sales_report/">Gestión de ventas</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/catalogue">Catálogo</a>
                </li>
                {% if not user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="/order/my_orders">Pedidos</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/about">Sobre Nosostros</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <div class="d-flex align-items-center">
                        <p class="nav-link m-0 me-3">
                            <strong>{{ user.email }}</strong>
                        </p>
                        <a class="btn btn-secondary me-3" href="/auth/logout">Cerrar Sesion</a>
                    </div>
                {% endif %}
                {% if not user.is_authenticated %}
                    <div class="d-flex align-items-center">
                        <a class="btn btn-secondary me-3" href="/auth/login">Iniciar Sesion</a>
                        <a class="btn btn-secondary me-3" href="/auth/signup">Registrarse</a>
                    </div>
                {% endif %}

                {% if not user.is_staff %}
                    {% if cart|length > 0 %}
                        <div class="d-flex align-items-center">
                            <a class="btn btn-light me-3" href="/order/create">Compra rápida</a>
                        </div>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/cart">
                            <img src="{% static 'img/cart.png' %}" alt="Cart" width="40" height="40">
                            <span class="badge bg-secondary">
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            {{ total_items }}
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                {% endif %}
              </span>
                    </a>
                </li>
            </ul>
        </div>
</nav>
<main>
    {% block content %}
    {% endblock %}
    {% block additional_content %}
    {% endblock %}
</main>
<footer class="container-fluid text-white text-center py-3" style="background-color: #ececec;">
    <img src="{% static 'US-marca-digital_0.png' %}" alt="US" class="img-fluid col-md-2">
    <p class="mt-3 text-dark">© 2023 US - Todos los derechos reservados</p>
</footer>
</body>
</html>

ardueshop/base/templates/base/home.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}

    <style>
        .banner {
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            background-image: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)), url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }
    </style>

    <div class="banner">
        <div class="text-center text-white">
            <h1 class="display-1">¡Bienvenido a ArduEshop!</h1>
            <h3>Descubre el mundo Arduino</h3>
            <div class="mx-auto" style="max-width: 50%;">
                <!-- Línea divisoria -->
                <hr class="border border-white">
            </div>
        </div>

        <div class="d-flex justify-content-between">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <p class="text-center text-white">¿Qué estás buscando?</p>
                <form method="get" action="{% url 'catalogue:search_products' %}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="product_name" placeholder="Nombre del producto"
                               aria-label="Nombre del producto">
                    </div>
                    <div class="input-group mb-3">
                        <select class="form-select" name="product_category" aria-label="Categoría del producto">
                            <option value="" selected>Selecciona una categoría</option>
                            {% for category in categories %}
                                <option value="{{ category }}">{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="min_price" placeholder="Precio mínimo"
                               aria-label="Precio mínimo">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">€</span>
                        </div>
                        <input type="text" class="form-control" name="max_price" placeholder="Precio máximo"
                               aria-label="Precio máximo">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon2">€</span>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center gap-2">
                        <a class="btn btn-outline-light" href="{% url 'product:catalogue' %}">Explorar el catálogo</a>
                        <button type="submit" class="btn btn-outline-light">Buscar</button>
                    </div>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

{% endblock %}

{% block additional_content %}
<div class="row p-4 mx-auto bg-dark d-flex justify-content-center">
    <div class="col-md-12 mb-2">
        <h2 class="text-center text-white">PRODUCTOS DESTACADOS</h2>
    </div>
    {% for product in products %}
        <div class="col-3 product-card" data-category="{{ product.category.name }}">
            <div class="card">
                <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title mb-0"><a class="text-dark"
                                                   href="/product/{{ product.id }}">{{ product.name }}</a>
                    </h5>
                    <p class="card-text">{{ product.category.name }}</p>
                    <div class="d-flex justify-content-between">
                        <h6 class="mb-0">{{ product.price }} €</h6>
                        {% if product.stock > 0 %}
                            <div class="d-flex align-items-center gap-1">
                                <i class="fas fa-check-circle text-success"></i>
                                <h6 class="text-success mb-0">Disponible</h6>
                            </div>
                        {% else %}
                            <div class="d-flex align-items-center gap-1">
                                <i class="fas fa-times-circle text-danger"></i>
                                <h6 class="text-danger mb-0">Agotado</h6>
                            </div>
                        {% endif %}
                    </div>
                    <form class="add-to-cart-form mt-3" action="{% url 'cart:cart_add' product.id %}"
                          method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <div class="input-group mt-2">
                                <label class="input-group-text"
                                       for="quantity_{{ product.id }}">Cantidad</label>
                                <input type="number" class="form-control" id="quantity_{{ product.id }}"
                                       name="quantity" min="1" value="1">
                            </div>
                            <button type="submit" class="btn btn-success mt-2">Añadir</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

ardueshop/base/templates/base/sales_report.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}- Gestión de ventas{% endblock %}
{% block content %}
    <div class="dashboard container mt-4">
        <h2>Gestión de ventas</h2>
        
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Número de pedidos (Últimos 30 días)</h5>
                        <p class="card-text">{{ number_of_orders_last_30_days }}</p>
                    </div>
                </div>
                
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Precio medio de pedidos (Últimos 30 días)</h5>
                        <p class="card-text">{{ average_price_last_30_days|floatformat:2  }} €</p>
                    </div>
                </div>
                
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Beneficios totales</h5>
                        <p class="card-text">{{ total_benefits }} €</p>
                    </div>
                </div>
                
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Beneficios (Últimos 30 días)</h5>
                        <p class="card-text">{{ total_price_last_30_days }} €</p>
                    </div>
                </div>
                
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Método de envío preferido (Últimos 30 días)</h5>
                        <p class="card-text">{{ preferred_shipping_option }}</p>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Productos más populares (Últimos 30 días)</h5>
                        <ol class="card-text">
                            {% for product_details in popular_products %}
                                <li><a href="/product/{{product_details.product.id}}">{{ product_details.product.name }}</a> - Cantidad vendida: {{ product_details.total_quantity }}</li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}