ardueshop/ardueshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
        path("product/", include("product.urls", namespace="product")),
        path("catalogue/", include("product.urls", namespace="catalogue")),
        path("cart/", include("cart.urls", namespace="cart")),
        path("order/", include("order.urls", namespace="order")),
        path("payment/", include("payment.urls", namespace="payment")),
        path(
            "", include("base.urls")
        ),  # This path must be the last one because it will match any URL
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

ardueshop/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path('order_not_found/', views.order_not_found, name='order_not_found'),
    path('sales_report/', views.sales_report, name='sales_report')
]

ardueshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

ardueshop/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path('<int:id>/', views.order_status, name='order_status'),
    path("<int:order_id>/claim/new_claim", views.new_claim, name="do_claim"),
    path("claim/<int:claim_id>", views.claim, name="claim"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("order_placed/", views.order_placed, name="order_placed"),
    path("all_orders/", views.all_orders, name="all_orders"),
    path("claims/", views.list_claims, name="list_claims"),
    path('order_not_found/', views.order_not_found, name='order_not_found')
]

ardueshop/product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('', views.catalogue, name='catalogue'),
    path('<int:id>/publishOpinion/', views.publish_opinion, name='publish_opinion'),
    path("search/", views.search_products, name="search_products"),
]

ardueshop/cart/models.py
from django.db import models

# Create your models here.

ardueshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 99)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

ardueshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )
    return redirect("catalogue:catalogue")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

ardueshop/cart/templates/cart/detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
    - Tu cesta de la compra
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-12 text-center">
      <h1>Tu cesta de la compra</h1>
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table table-striped table-bordered">
        <thead class="table-dark">
          <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Eliminar</th>
            <th>Precio unitario</th>
            <th>Precio</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
            <tr>
              <td>
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static " img/no_image.png" %}{% endif%}"
                class="img-thumbnail" alt="{{ product.name }}" style="width: 100px; height: 100px;">
              </td>
              <td>{{ product.name }}</td>
              <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.override }}
                  <button type="submit" class="btn btn-primary btn-sm">Actualizar</button>
                  {% csrf_token %}
                </form>
              </td>
              <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                  {% csrf_token %}
                </form>
              </td>
              <td class="num">{{ item.price }} €</td>
              <td class="num">{{ item.total_price }} €</td>
            </tr>
            {% endwith %}
          {% endfor %}
          
          <!-- Añadir la entrada de envío -->
          {% if cart|length > 0 %}
          <tr>
            <td colspan="5" class="text-end">Envío</td>
            {% if cart.get_total_price_without_shipping >= 50 %}
            <td>Gratis</td>
            {% else %}
            <td class="num">{{ cart.get_shipping }} €</td>
            {% endif %}
          </tr>
          {% endif %}

          <tr class="table-secondary">
            <td colspan="5" class="text-end">Total</td>
            {% if cart.get_total_price_without_shipping >= 50 or cart|length == 0 %}
            <td class="num">{{ cart.get_total_price_without_shipping }} €</td>
            {% else %}
            <td class="num">{{ cart.get_total_price }} €</td>
            {% endif %}
          </tr>
        </tbody>
      </table>
      <p class="text-end">
        <a href="{% url "catalogue:catalogue" %}" class="btn btn-primary">Continuar comprando</a>
        {% if cart %}
        <a href="{% url "order:order_create" %}" class="btn btn-success">Realizar pedido</a>
        {% endif %}
      </p>
    </div>
  </div>
</div>
{% endblock %}


<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        // Obtén los elementos del DOM
        let shippingCostElement = document.querySelector('.shipping-cost');
        let totalCostElement = document.querySelector('.total-cost');

        // Convierte los costos a números
        let shippingCost = parseFloat(shippingCostElement.innerText);
        let totalCost = parseFloat(totalCostElement.innerText);

        // Verifica si se debe cobrar el envío
        if (totalCost <= 50) {
            totalCost += shippingCost;
        }

        // Actualiza el costo total en el DOM
        totalCostElement.innerText = totalCost.toFixed(2);
    });
</script>