ardueshop/ardueshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
        path("product/", include("product.urls", namespace="product")),
        path("catalogue/", include("product.urls", namespace="catalogue")),
        path("cart/", include("cart.urls", namespace="cart")),
        path("order/", include("order.urls", namespace="order")),
        path("payment/", include("payment.urls", namespace="payment")),
        path(
            "", include("base.urls")
        ),  # This path must be the last one because it will match any URL
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

ardueshop/authentication/urls.py
from django.contrib import admin
from django.urls import path
from authentication import views as authentication_views

urlpatterns = [
    path('login/', authentication_views.login_view, name='login'),
    path('signup/', authentication_views.signup_view, name='signup'),
    path('logout/', authentication_views.logout_view, name='logout'),
]

ardueshop/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path('order_not_found/', views.order_not_found, name='order_not_found'),
    path('sales_report/', views.sales_report, name='sales_report')
]

ardueshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

ardueshop/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path('<int:id>/', views.order_status, name='order_status'),
    path("<int:order_id>/claim/new_claim", views.new_claim, name="do_claim"),
    path("claim/<int:claim_id>", views.claim, name="claim"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("order_placed/", views.order_placed, name="order_placed"),
    path("all_orders/", views.all_orders, name="all_orders"),
    path("claims/", views.list_claims, name="list_claims"),
    path('order_not_found/', views.order_not_found, name='order_not_found')
]

ardueshop/product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('', views.catalogue, name='catalogue'),
    path('<int:id>/publishOpinion/', views.publish_opinion, name='publish_opinion'),
    path("search/", views.search_products, name="search_products"),
]

ardueshop/order/models.py
from django.db import models
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from decouple import config
from product.models import Product

from django.utils.html import strip_tags


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    SHIPPING_STATUS_CHOICES = (
        ("Pendiente", "Pendiente"),
        ("Enviado", "Enviado"),
        ("Entregado", "Entregado"),
    )

    shipping_status = models.CharField(
        max_length=20, choices=SHIPPING_STATUS_CHOICES, default="Pendiente"
    )

    SHIPPING_METHOD_CHOICES = (
        ("Entrega estándar", "Entrega estándar"),
        ("Recogida en tienda", "Recogida en tienda"),
    )
    shipping_method = models.CharField(
        max_length=25, choices=SHIPPING_METHOD_CHOICES, default="Entrega estándar"
    )

    PAYMENT_METHOD_CHOICES = (
        ("Tarjeta", "Tarjeta"),
        ("Contra-reembolso", "Contra-reembolso"),
    )

    payment_method = models.CharField(
        max_length=20, choices=PAYMENT_METHOD_CHOICES, default="Tarjeta"
    )

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]

    def get_total_cost(self):
        return self.get_order_cost() + self.get_shipping_cost()

    def get_order_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_shipping_cost(self):
        if self.get_order_cost() < 50 and self.shipping_method == "Entrega estándar":
            return 5
        else:
            return 0

    def send_confirmation_email(self):
        subject = "ArduEshop - Confirmación de pedido"
        html_message = render_to_string(
            "order/order_confirmation_email.html", {"order": self}
        )
        plain_message = strip_tags(html_message)
        email = EmailMultiAlternatives(
            subject, plain_message, config("EMAIL_HOST_USER"), [self.email]
        )
        email.attach_alternative(html_message, "text/html")
        email.send()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def get_cost(self):
        return self.price * self.quantity


class Claim(models.Model):
    order = models.ForeignKey(Order, related_name="order", on_delete=models.CASCADE)
    comment = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    CLAIM_STATUS_CHOICES = (
        ("Pendiente", "Pendiente"),
        ("Atendida", "Atendida"),
    )

    claim_status = models.CharField(
        max_length=20, choices=CLAIM_STATUS_CHOICES, default="Pendiente"
    )

    response = models.TextField(blank=True)

    def __str__(self):
        return f"Reclamacion #{self.id} - {self.order.email}"
    
    class Meta:
        ordering = ["-creation_date"]
        indexes = [
            models.Index(fields=["-creation_date"]),
        ]

ardueshop/order/forms.py
from django import forms
from .models import Order, Claim


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "email",
            "first_name",
            "last_name",
            "address",
            "postal_code",
            "city",
            "shipping_method",
            "payment_method",
        ]
        labels = {
            "email": "Correo Electrónico",
            "first_name": "Nombre",
            "last_name": "Apellido",
            "address": "Dirección",
            "postal_code": "Código Postal",
            "city": "Ciudad",
            "shipping_method": "Método de entrega",
            "payment_method": "Método de Pago",
        }


class EmailPickerForm(forms.Form):
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Correo Electrónico",
                "class": "form-control",
            }
        ),
    )


class ClaimForm(forms.ModelForm):
    comment = forms.CharField(
        max_length=254,
        label="Descripcion",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Descripcion de la reclamacion",
                "class": "form-control",
            }
        ),
    )

    class Meta:
        model = Claim
        fields = ["comment"]

class ClaimResponseForm(forms.ModelForm):
    response = forms.CharField(
        max_length=1024,
        label="Respuesta",
        widget=forms.Textarea(
            attrs={
                "placeholder": "Respuesta a la reclamación",
                "class": "form-control",
            }
        ),
    )

    class Meta:
        model = Claim
        fields = ["response"]

ardueshop/order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.models import User
from decimal import Decimal
from .models import Claim, OrderItem, Order
from .forms import  EmailPickerForm, OrderCreateForm, ClaimForm, ClaimResponseForm
from datetime import timezone

from payment.forms import SaveDataForm
from cart.cart import Cart
from authentication.models import ArduUser
import stripe
from django.contrib.auth.decorators import login_required


# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def my_orders(request):
    if request.user.is_authenticated:
        orders = Order.objects.filter(email=request.user.email)
        for order in orders:
            order.claims = Claim.objects.filter(order=order)
        return render(request, "order/my_orders.html", {"orders": orders})
    else:
        return render(request, "order/not_authenticated_user.html")

def all_orders(request):
    if request.user.is_authenticated and request.user.is_staff:
        orders = Order.objects.all()
        return render(request, "order/all_orders.html", {"orders": orders})
    else:
        return render(request, "order/not_authenticated_user.html")
    

def order_create(request):
    cart = Cart(request)
    if request.method == "POST":
        if request.user.is_authenticated:
            request.POST._mutable = True
            request.POST["email"] = request.user.email
            request.POST._mutable = False
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )

            cart.clear()

            request.session["order_id"] = order.id

            if order.payment_method == "Tarjeta":
                return payment_process(request, order)
            else:
                order.shipping_status = "Enviado"
                order.save()
                # Update product stock
                for item in order.items.all():
                    item.product.stock -= item.quantity
                    item.product.save()
                # Send confirmation email
                order.send_confirmation_email()
                return redirect(reverse("order:order_placed"))

    else:
        no_stock_products = []
        for item in cart:
            if item["quantity"] > item["product"].stock:
                no_stock_products.append(item["product"])
        if not request.user.is_staff:
            if len(no_stock_products) > 0:
                messages.error(
                    request,
                    "No hay suficiente stock de los siguientes productos: {}".format(
                        ", ".join([str(p) for p in no_stock_products])
                    ),
                )
                return redirect(reverse("cart:cart_detail"))

            if request.user.is_authenticated:
                ardu_user = ArduUser.objects.get(user=request.user)
                form = OrderCreateForm(
                    initial={
                        "email": request.user.email,
                        "first_name": request.user.first_name,
                        "last_name": request.user.last_name,
                        "address": ardu_user.address,
                        "postal_code": ardu_user.postal_code,
                        "city": ardu_user.city,
                    }
                )
            else:
                form = OrderCreateForm()
            return render(request, "order/create.html", {"form": form, "cart": cart})
        else:
            return render(request, "order/admin_order_not_authorized.html")

def order_status(request, id):
    try:
        order = Order.objects.get(id=id)
    except Order.DoesNotExist:
        return redirect('order_not_found')
    return render(request, "order/order_status.html", {"order": order})

def order_not_found(request):
    return render(request, "order/order_not_found.html")

def order_placed(request):
    order = Order.objects.get(id=request.session.get("order_id"))
    form = SaveDataForm()
    if request.method == "POST":
        form = SaveDataForm(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            ardu_user = ArduUser.objects.get(user=user)
            if form.cleaned_data["save_data_checkbox"]:
                user.first_name = order.first_name
                user.last_name = order.last_name
                user.save()
                ardu_user.address = order.address
                ardu_user.postal_code = order.postal_code
                ardu_user.city = order.city
                ardu_user.save()

            else:
                user.first_name = ""
                user.last_name = ""
                user.save()
                ardu_user.address = None
                ardu_user.postal_code = None
                ardu_user.city = None
                ardu_user.save()

            return redirect(reverse("catalogue:catalogue"))

    return render(request, "order/order_placed.html", {"order": order, "form": form})


def new_claim(request, order_id):
    if request.method == "POST":
        form = ClaimForm(request.POST)
        if form.is_valid():
            claim = form.save(commit=False)
            # claim.creation_date = timezone.now()
            claim.order = Order.objects.get(id=order_id)
            claim.save()
            return redirect("order:claim", claim_id=claim.id)
    else:
        form = ClaimForm()

    return render(request, "order/new_claim.html", {"form": form})


def claim(request, claim_id):
    if request.method == "POST":
        user = request.user
        if user.is_staff:
            form = ClaimResponseForm(request.POST)
            if form.is_valid():
                claim = Claim.objects.get(id=claim_id)
                claim.response = form.cleaned_data.get('response')
                claim.claim_status = "Atendida"
                claim.save()
                return redirect("order:claim", claim_id=claim.id)
            
    else:
        claim = Claim.objects.get(id=claim_id)
        user = request.user
        form = None
        if user.is_staff:
            form = ClaimResponseForm()
    return render(request, "order/claim.html", {"claim": claim, "form": form})


@login_required(login_url="/auth/login")
def list_claims(request):
    user = request.user
    if user.is_staff:
        claims = Claim.objects.all()

        return render(request, "order/claim_listing.html", {"claims": claims})
    else:
        return redirect("/auth/login")
    


# Auxiliar functions:


def payment_process(request, order):
    success_url = request.build_absolute_uri(reverse("payment:completed"))
    cancel_url = request.build_absolute_uri(reverse("payment:canceled"))

    # Stripe checkout session data
    session_data = {
        "mode": "payment",
        "client_reference_id": order.id,
        "success_url": success_url,
        "cancel_url": cancel_url,
        "line_items": [],
    }

    # Add order items to the Stripe checkout session
    for item in order.items.all():
        session_data["line_items"].append(
            {
                "price_data": {
                    "unit_amount": int(item.price * Decimal("100")),
                    "currency": "eur",
                    "product_data": {
                        "name": item.product.name,
                    },
                },
                "quantity": item.quantity,
            }
        )

    if order.get_total_cost() < 50 and order.shipping_method == "Entrega estándar":
        session_data["line_items"].append(
            {
                "price_data": {
                    "unit_amount": int(order.get_shipping_cost() * Decimal("100")),
                    "currency": "eur",
                    "product_data": {
                        "name": "Costes de envío",
                    },
                },
                "quantity": 1,
            }
        )

    # Create Stripe checkout session
    session = stripe.checkout.Session.create(**session_data)

    # Redirect to Stripe payment form
    return redirect(session.url, code=303)

ardueshop/order/templates/order/admin_order_not_authorized.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Admin not authorized{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 text-center" style="padding-top: 20px;">
                <h3>El administrador no puede realizar pedidos</h3>
                <p class="lead">Inicia sesión con un usuario que no sea el administrador para realizar pedidos</p>
                <a class="btn btn-secondary btn-lg" href="/auth/login">Iniciar Sesion</a>
            </div>
        </div>
    </div>

{% endblock %}

ardueshop/order/templates/order/all_orders.html
{% extends 'base/base.html' %} 
{% load static %} 

{% block title %} - Pedidos {%endblock %} 

{% block content %} 
{% if orders.count == 0 %}
<div class="container text-center" style="padding-top: 20px">
  <h4>No hay pedidos</h4>
</div>
{% endif %}

<div class="container" style="padding-top: 20px">
  <div class="mb-3">
    <label for="statusFilter" class="form-label">Filtrar por estado:</label>
    <select id="statusFilter">
      <option value="all">Todas</option>
      <option value="Pendiente">Pendiente</option>
      <option value="Enviado">Enviado</option>
      <option value="Entregado">Entregado</option>
    </select>
  </div>
  <table class="table table-striped" id="orderTable">
    <thead>
      <tr>
        <th>Identificador</th>
        <th>Correo electrónico</th>
        <th>Fecha de creación</th>
        <th>Estado</th>
        <th>Pagado</th>
        <th>Método de envío</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr data-category="{{ order.shipping_status }}">
        <td>
          <p>Pedido {{order.id}}</p>
        </td>
        <td>
          <p>{{order.email}}</p>
        </td>
        <td>
          <time datetime="{{order.created|date:'d/M/y h:m'}}"
            >{{order.created|date:'d/M/y h:m'}}</time
          >
        </td>
        <td>
          <p>{{order.shipping_status}}</p>
        </td>
        <td>
          {% if order.paid %}
          <p>Si</p>
          {% else %}
          <p>No</p>
          {% endif %}
        </td>
        <td>
          <p>{{order.shipping_method}}</p>
        </td>
        <td>
          <a href="/admin/order/order/{{ order.id }}"> Gestionar </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const statusFilter = document.getElementById("statusFilter");
    const tableRows = document.querySelectorAll("#orderTable tbody tr");

    statusFilter.addEventListener("change", function () {
      const selectedStatus = statusFilter.value;

      tableRows.forEach((row) => {
        if (
          selectedStatus === "all" ||
          row.getAttribute("data-category") === selectedStatus
        ) {
          row.style.display = "table-row";
        } else {
          row.style.display = "none";
        }
      });
    });
  });
</script>
{% endblock %}

ardueshop/order/templates/order/claim.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
  - Reclamación de pedido
{% endblock %}

{% block content %}

<div class="container" style="padding-top: 20px;">
  <h4>Fecha de creación</h4>
  <time> {{claim.creation_date}} </time>
  
  <h4>Descripción</h4>
  <p> {{claim.comment}} </p>
  
  {% if claim.claim_status == "Atendida" %}
  <h4>Respuesta</h4>
  <p> {{claim.response}} </p>
  {% endif%}

  {% if user.is_staff and claim.claim_status == "Pendiente"%}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary me-3">Enviar Respuesta</button>
  </form>
  {% endif %}
</div>

{% endblock %}

ardueshop/order/templates/order/claim_listing.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}- Reclamaciones{% endblock %} 

{% block content %}
<div class="container mt-4">
  <div class="mb-3">
    <label for="statusFilter" class="form-label">Filtrar por estado:</label>
    <select id="statusFilter">
      <option value="all">Todas</option>
      <option value="Pendiente">Pendiente</option>
      <option value="Atendida">Atendida</option>
    </select>
  </div>
  <table class="table" id="claimTable">
    <thead>
      <tr>
        <th>Pedido</th>
        <th>Detalles</th>
        <th>Estado</th>
        <th>Fecha</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
      {% if not claims %}
      <tr>
        <td colspan="5">No hay reclamaciones</td>
      </tr>
      {% endif %} {% for claim in claims %}
      <tr data-category="{{ claim.claim_status }}">
        <td>{{ claim.order.id }}</td>
        <td>{{ claim.comment }}</td>
        <td>{{ claim.claim_status }}</td>
        <td>{{ claim.creation_date }}</td>
        <td>
          <a href="/order/claim/{{ claim.id }}"> Gestionar </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const statusFilter = document.getElementById("statusFilter");
    const tableRows = document.querySelectorAll("#claimTable tbody tr");

    statusFilter.addEventListener("change", function () {
      const selectedStatus = statusFilter.value;

      tableRows.forEach((row) => {
        if (
          selectedStatus === "all" ||
          row.getAttribute("data-category") === selectedStatus
        ) {
          row.style.display = "table-row";
        } else {
          row.style.display = "none";
        }
      });
    });
  });
</script>

{% endblock %}

ardueshop/order/templates/order/create.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
    - Realizar pedido
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Realizar pedido</h1>
    <div>
        <h3>Tu pedido:</h3>
        <ul class="list-group">
            {% for item in cart %}
            <li class="list-group-item">
                {{ item.quantity }}x {{ item.product.name }}
                <span class="float-end">{{ item.total_price }} €</span>
            </li>
            {% endfor %}

            {% if cart.get_total_price_without_shipping < 50 %}
            <li class="list-group-item">
                Envio
                <span class="float-end" id="shipping_cost"> 5 €</span>
            </li>
            {% else %}
            <li class="list-group-item">
                Envio
                <span class="float-end" id="shipping_cost"> 0 €</span>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="d-flex justify-content-between my-4">
        <div class="col-md-3"></div>
        <div class="col-md-4 border border-2 rounded p-3">
            <p id="total_cost">Total: {{ cart.get_total_price }} €</p>
            <form method="post" class="mt-4">
                {% csrf_token %}
                <div class="d-flex justify-content-between">
                    <p>{{ form.email.label_tag }}</p>
                    {% if user.is_authenticated %}
                        <p>{{ form.email.value }}</p>
                    {% else %}
                        <p>{{ form.email }}</p>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.first_name.label_tag }}</p>
                    <p>{{ form.first_name }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.last_name.label_tag }}</p>
                    <p>{{ form.last_name }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.address.label_tag }}</p>
                    <p>{{ form.address }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.postal_code.label_tag }}</p>
                    <p>{{ form.postal_code }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.city.label_tag }}</p>
                    <p>{{ form.city }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.shipping_method.label_tag }}</p>
                    <p onchange="checkShipping({{ cart.get_total_price_without_shipping }})">{{ form.shipping_method }}</p>
                </div>
                <div class="d-flex justify-content-between">
                    <p>{{ form.payment_method.label_tag }}</p>
                    <p>{{ form.payment_method }}</p>
                </div>
                <p class="d-flex justify-content-center mt-3">
                    <a href="{% url "cart:cart_detail" %}" class="btn btn-danger me-3">Volver a la cesta</a>
                    <input type="submit" value="Confirmar" class="btn btn-primary">
                </p>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>

<script>
    function checkShipping(price) {
      if (price < 50) {
          var selectedOption = document.getElementById("id_shipping_method").value;
          var costText = document.getElementById("shipping_cost");
          var totalCost = document.getElementById("total_cost");
          if (selectedOption === "Entrega estándar") {
            costText.textContent = " 5 €";
            totalCost.textContent = "Total " + (price + 5).toString() + " €";
          } else {
            costText.textContent = " 0 €"; // Clear the text if another option is selected
            totalCost.textContent = "Total " + price.toString() + " €";
          }
      }
    }
</script>

{% endblock %}

ardueshop/order/templates/order/my_orders.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
  - Mis pedidos
{% endblock %}

{% block content %}

{% if orders.count == 0 %}
  <div class="container text-center" style="padding-top: 20px;">
    <h4>No hay pedidos</h4>
  </div>
{% endif %}

{% for order in orders %}
<div class="container" style="padding-top: 20px;">
  <table class="table table-striped">
    <tr>
      <th>Correo electrónico</th>
      <th>Dirección</th>
      <th>Ciudad</th>
      <th>Código Postal</th>
      <th>Fecha de creación</th>
      <th>Estado</th>
      <th>Pagado</th>
      <th>Método de envío</th>      
    </tr>
    <tr>
      <td>
        <p> {{order.email}} </p>
      </td>
      <td>
        <p> {{order.address}} </p>
      </td>
      <td>
        <p> {{order.city}} </p>
      </td>
      <td>
        <p> {{order.postal_code}} </p>
      </td>
      <td>
        <time datetime="{{order.created|date:'d/M/y h:m'}}">{{order.created|date:'d/M/y h:m'}}</time>
      </td>
      <td>
        <p> {{order.shipping_status}} </p>
      </td>
      <td>
        {% if order.paid %}
          <p>Si</p>
        {% else %}
          <p>No</p>
        {% endif %}
      </td>
      <td>
        <p> {{order.shipping_method}} </p>
      </td>
    </tr>
    <tr>
    </tr>
    <table class="table table-striped">
      <tr>
        <th>Reclamaciones</th>
        <th>Estado</th>
      </tr>
      {% if order.claims.all.count == 0 %}
        <tr>
          <td>No hay reclamaciones</td>
        </tr>
      {% endif %}
      {% for claim in order.claims.all %}
        {% if claim != None %}
          <tr>
            <td><a href="{% url 'order:claim' claim_id=claim.id %}" style="color: black;">{{ claim.comment }}</a></td>
            <td>{{ claim.claim_status }}</td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
    <a href="{% url 'order:do_claim' order_id=order.id %}" class="btn btn-secondary me-3">Nueva reclamación</a>

    <!-- Espacio entre tablas -->
    <p>


    </p>
    <!-- Espacio entre tablas -->

    <table class="table table-striped">
      <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio</th>
      </tr>
      {% for item in order.items.all %}
        <tr>
          <td>{{ item.product.name }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.price }} €</td>
        </tr>
      {% endfor %}
      <tr>
        <td><strong>Total: </strong></td>
        <td></td>
        <td><strong>{{ order.get_total_cost }} €</strong></td>
  </table>
  <hr>
</div>
{% endfor %}
{% endblock %}

ardueshop/order/templates/order/new_claim.html
{% extends 'base/base.html' %}

{% block title %}
  - Nueva reclamación
{% endblock %}

{% block content %}

<div class="container" style="padding-top: 20px;">
  <h4>Nueva Reclamación</h4>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary me-3">Enviar Reclamación</button>
  </form>
</div>
{% endblock %}

ardueshop/order/templates/order/not_authenticated_user.html
{% extends 'base/base.html' %}

{% block title %}
  - Consulta de pedidos
{% endblock %}

{% block content %}
    {% include 'order/id_search.html' %}

    <div class="container text-center" style="padding-top: 20px;">
        <h4 class="mb-2">Necesitas autenticarte para acceder al listado de tus pedidos</h4>
        <a href="{% url 'authentication:login' %}" class="btn btn-primary">Acceder</a>
        <a href="{% url 'authentication:signup' %}" class="btn btn-primary">Registrarse</a>
    </div>
{% endblock %}

ardueshop/order/templates/order/order_placed.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}- Pedido realizado{% endblock %}

{% block content %}

<div class="container mt-4">
    <div class="card text-center">
        <div class="card-body">
            <h1 class="card-title">¡Pedido realizado! El ID para el seguimiento de tu pedido es {{request.session.order_id}}</h1>
            <p class="card-text"> Puedes consultar el estado de tu pedido en
                <a href="{% url "order:my_orders" %}">este enlace</a>.
            </p>
            <p class="card-text">Gracias por tu compra.</p>
            <p class="card-text">Recibirás un correo electrónico de confirmación pronto.</p>

            {% if user.is_authenticated %}
            <form method="post" class="form-check">
                {% csrf_token %}
                <div class="mb-4">
                    {{ form.save_data_checkbox }}
                    <label class="form-check-label" for="{{ form.save_data_checkbox.id_for_label }}">
                        Guardar mis datos para futuras compras
                    </label>
                </div>
                <input type="submit" value="Volver a la tienda" class="btn btn-primary">
            </form> 
            {% else %}
            <a href="{% url "product:catalogue" %}" class="btn btn-primary">Volver a la tienda</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}